name: Trigger PIAS CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "infra/**"
jobs:
  PPIAS:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Invoke PIAS workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ci
          repo: IEA-Paris/PIAS
          token: ${{ secrets.SERVICE_USER_PAT }}
          ref: refs/heads/main
          inputs: '{ "name": "PPIAS", "domain": "paris" }'
